package audio

// List isn't exhaustive
// TODO: expand it? Not sure backends support exhaustive list though, would need to test language by language... would need to ignore content of transcription.
// -> Hard to validate source audio language is as advertised as well.
var AllowedIsoLanguages = struct {
	Afrikaans       string
	Albanian        string
	Amharic         string
	Arabic          string
	Armenian        string
	Azerbaijani     string
	Basque          string
	Belarusian      string
	Bengali         string
	Bosnian         string
	Bulgarian       string
	Catalan         string
	Cebuano         string
	Chinese         string
	Corsican        string
	Croatian        string
	Czech           string
	Danish          string
	Dutch           string
	English         string
	Esperanto       string
	Estonian        string
	Filipino        string
	Finnish         string
	French          string
	Frisian         string
	Galician        string
	Georgian        string
	German          string
	Greek           string
	Gujarati        string
	Haitian_Creole  string
	Hausa           string
	Hawaiian        string
	Hebrew          string
	Hindi           string
	Hmong           string
	Hungarian       string
	Icelandic       string
	Igbo            string
	Indonesian      string
	Irish           string
	Italian         string
	Japanese        string
	Javanese        string
	Kannada         string
	Kazakh          string
	Khmer           string
	Kinyarwanda     string
	Korean          string
	Kurdish         string
	Kyrgyz          string
	Lao             string
	Latin           string
	Latvian         string
	Lithuanian      string
	Luxembourgish   string
	Macedonian      string
	Malagasy        string
	Malay           string
	Malayalam       string
	Maltese         string
	Maori           string
	Marathi         string
	Mongolian       string
	Myanmar_Burmese string
	Nepali          string
	Norwegian       string
	Pashto          string
	Persian         string
	Polish          string
	Portuguese      string
	Punjabi         string
	Romanian        string
	Russian         string
	Samoan          string
	Scots_Gaelic    string
	Serbian         string
	Sesotho         string
	Shona           string
	Sindhi          string
	Sinhala         string
	Slovak          string
	Slovenian       string
	Somali          string
	Spanish         string
	Sundanese       string
	Swahili         string
	Swedish         string
	Tajik           string
	Tamil           string
	Telugu          string
	Thai            string
	Turkish         string
	Ukrainian       string
	Urdu            string
	Uzbek           string
	Vietnamese      string
	Welsh           string
	Xhosa           string
	Yiddish         string
	Yoruba          string
	Zulu            string
}{
	Afrikaans:       "af",
	Albanian:        "sq",
	Amharic:         "am",
	Arabic:          "ar",
	Armenian:        "hy",
	Azerbaijani:     "az",
	Basque:          "eu",
	Belarusian:      "be",
	Bengali:         "bn",
	Bosnian:         "bs",
	Bulgarian:       "bg",
	Catalan:         "ca",
	Cebuano:         "ceb",
	Chinese:         "zh",
	Corsican:        "co",
	Croatian:        "hr",
	Czech:           "cs",
	Danish:          "da",
	Dutch:           "nl",
	English:         "en",
	Esperanto:       "eo",
	Estonian:        "et",
	Filipino:        "tl",
	Finnish:         "fi",
	French:          "fr",
	Frisian:         "fy",
	Galician:        "gl",
	Georgian:        "ka",
	German:          "de",
	Greek:           "el",
	Gujarati:        "gu",
	Haitian_Creole:  "ht",
	Hausa:           "ha",
	Hawaiian:        "haw",
	Hebrew:          "he",
	Hindi:           "hi",
	Hmong:           "hmn",
	Hungarian:       "hu",
	Icelandic:       "is",
	Igbo:            "ig",
	Indonesian:      "id",
	Irish:           "ga",
	Italian:         "it",
	Japanese:        "ja",
	Javanese:        "jv",
	Kannada:         "kn",
	Kazakh:          "kk",
	Khmer:           "km",
	Kinyarwanda:     "rw",
	Korean:          "ko",
	Kurdish:         "ku",
	Kyrgyz:          "ky",
	Lao:             "lo",
	Latin:           "la",
	Latvian:         "lv",
	Lithuanian:      "lt",
	Luxembourgish:   "lb",
	Macedonian:      "mk",
	Malagasy:        "mg",
	Malay:           "ms",
	Malayalam:       "ml",
	Maltese:         "mt",
	Maori:           "mi",
	Marathi:         "mr",
	Mongolian:       "mn",
	Myanmar_Burmese: "my",
	Nepali:          "ne",
	Norwegian:       "no",
	Pashto:          "ps",
	Persian:         "fa",
	Polish:          "pl",
	Portuguese:      "pt",
	Punjabi:         "pa",
	Romanian:        "ro",
	Russian:         "ru",
	Samoan:          "sm",
	Scots_Gaelic:    "gd",
	Serbian:         "sr",
	Sesotho:         "st",
	Shona:           "sn",
	Sindhi:          "sd",
	Sinhala:         "si",
	Slovak:          "sk",
	Slovenian:       "sl",
	Somali:          "so",
	Spanish:         "es",
	Sundanese:       "su",
	Swahili:         "sw",
	Swedish:         "sv",
	Tajik:           "tg",
	Tamil:           "ta",
	Telugu:          "te",
	Thai:            "th",
	Turkish:         "tr",
	Ukrainian:       "uk",
	Urdu:            "ur",
	Uzbek:           "uz",
	Vietnamese:      "vi",
	Welsh:           "cy",
	Xhosa:           "xh",
	Yiddish:         "yi",
	Yoruba:          "yo",
	Zulu:            "zu",
}
